### ISSUE TITLE
Batch processing : create profil ?

### ISSUE THREAD

**Issue by Trogonite** [nomacs/nomacs#355] opened 2019-07-25 19:12 UTC

**Comment by Trogonite** [comment] 2019-07-25 19:14
hello, when I use batch processing, when I want to create a profile the program closes. I am on MX linux 18.3

**Comment by diemmarkus** [comment] 2019-08-07 06:49
hi, which nomacs version are you using?

**Comment by Trogonite** [comment] 2019-08-18 16:02
I use Nomac 3.8

**Comment by commander-keen** [comment] 2020-01-11 23:49
Duplicate of #300 
https://github.com/nomacs/nomacs/issues/300

**Closed** 2020-03-19 11:02 UTC
