### ISSUE TITLE
Crop fills in the wrong values in the Crop tool bar

### ISSUE THREAD

**Issue by haferburg** [nomacs/nomacs#1064] opened 2024-04-17 16:47 UTC
I needed to batch crop four 4k files. So I had to open one of them in a second window, and selected the crop region manually. I then copied the values from the crop toolbar over to the corresponding fields in the batch editor. The results were wrong.

As a workaround I had to drag the crop region, which triggered the tooltip, which displays the correct values. When I entered these values in the batch editor I got the correct results.

Unfortunately I can't make a screenshot because making a screenshot with Print doesn't work when the mouse button is pressed, which is necessary to display the tooltip. Sorry.

nomacs 3.12, Ubuntu 22.04

**Comment by leejuyuu** [comment] 2024-04-26 18:19
Sorry, I am not sure I follow correctly. Do you mean the crop region displayed in the toolbar (image below) is incorrect and different from the values displayed when dragging the crop rectangle handles?
![image](https://github.com/nomacs/nomacs/assets/46868116/b960fd4e-813c-42c2-b3f8-de01b2730bb6)

**Comment by leejuyuu** [comment] 2024-04-26 18:33
I seem to reproduce this (if my assumptions were correct) on 3.17.2295 (94e9ada), Arch Linux.

When the resize handles are dropped, the width and height of the rectangle in the input boxes are correct, but the x and y values are different from what was shown on the tooltip. 

https://github.com/nomacs/nomacs/assets/46868116/38e2cc7c-e7b3-43d6-a86d-d80730904729

@haferburg Can you confirm this is what you see?

**Comment by leejuyuu** [comment] 2024-04-26 18:49
Judging by the values, the x and y coordinates in the toolbar are tracking the center of the rectangle.

**Comment by leejuyuu** [comment] 2024-04-26 18:54
Could be duplicate of #944

**Comment by haferburg** [comment] 2024-05-03 09:44
Oh. Right. I can make a screencast and take screenshots from the video.

What I meant is that the tooltip here shows the correct values (left, top, width, height).
![image](https://github.com/nomacs/nomacs/assets/4941909/56737c3a-0cf0-4ac2-a223-ac85b17a3918)

But when you release the mouse button, it fills in the wrong values for x and y:
![image](https://github.com/nomacs/nomacs/assets/4941909/76ca858b-2a05-4e1d-8f8f-80883fb2c9a4)

Yes, looks like a duplicate.

**Comment by leejuyuu** [comment] 2024-05-03 17:06
Thanks for taking the time to confirm! I am going to close this as a duplicate. Please continue the discussion at #944.

**Closed by leejuyuu** 2024-05-03 17:06 UTC
Labels: duplicate
