### ISSUE TITLE
Bug: Exiting nomacs from fullscreen with middle mouse button (or keybinding) breaks successive program launches

### ISSUE THREAD

**Issue by BakedCookie** [nomacs/nomacs#1110] opened 2024-06-26 14:54 UTC
**Describe the bug**
Exiting nomacs when it's in fullscreen mode with either the middle mouse button or a custom keybinding (for File>Exit) has unusual effects on opening future images. The program ends up in a loop of window>fullscreen>window>fullscreen (...etc) when opening up new images. The windowed mode is missing the toolbar as well.

**To Reproduce**
1. Open any image by double clicking it in explorer
2. In nomacs double click of F11 to launch fullscreen
3. Exit with middle mouse button or custom keybinding (I'll be using ctrl+w for my keybinding)
4. Open the same image again (like in step 1)
5. Nomacs opens up windowed, is missing top toolbar and 'File, Edit, View, etc' menu
6. Close nomacs with keybinding (or closing the window with X works as well)
7. Open the same image again (same as step 4)
8. Nomacs opens up in fullscreen mode
9. Steps 3 through 8 repeat perpetually
10. At any point when nomacs is in fullscreen mode, hitting Esc will restore normal operation on future program launches

**Expected behavior**
nomacs should not cycle windowed and fullscreen modes just because I closed the program from fullscreen mode. It should always launch into windowed mode (without missing the toolbar as well) normally, or if using the -f flag, should always launch into fullscreen mode. How nomacs was shut down should not have an effect on what mode nomacs opens up in next time.

**Screenshots**
Normal windowed mode in step 1:
![A](https://github.com/nomacs/nomacs/assets/8518237/e6c86cee-eba3-4a3b-badb-01cdf8daacca)

Broken windowed mode in step 5:
![B](https://github.com/nomacs/nomacs/assets/8518237/b71cac32-7359-42f6-8a21-ec8eab5bc359)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version 3.17.2297 [x64]

**Additional context**
N/A

**Comment by scrubbbbs** [comment] 2024-06-26 21:20
Thanks for reporting. Feels like a duplicate of #550. Also I have posted a video there (last post) of what I believe you are describing, can you confirm it?

**Comment by BakedCookie** [comment] 2024-06-26 21:42
I wouldn't say this specific behavior is what's described in https://github.com/nomacs/nomacs/issues/550. There's no mention of this specific bug there, it's more to do with how Esc behaves and an enhancement of launching in fullscreen as a gui option. But as for the video you posted- yes, that's the exact same behavior I'm seeing on my end as well.

I actually thought Esc first exiting fullscreen, and then exiting the program on the second press was intended behavior haha. I guess it's not.

**Closed** 2024-07-20 08:20 UTC
