### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by 57382** [nomacs/nomacs#815] opened 2021-10-08 06:19 UTC
This is the best picture viewer I've ever used! Better than ImageGlass.

**Comment by abma** [comment] 2021-11-02 23:12
@sfiel @diemmarkus @timjerman 

will there be updates or is a fork needed?

**Comment by DJCrashdummy** [comment] 2021-11-04 08:18
sadly there is an [unanswered question about the status](https://github.com/nomacs/nomacs/issues/612) since early 2021... :frowning_face:

**Comment by fcore117** [comment] 2022-01-04 12:10
I really hope this project continues as it is the only biggest known open source image viewers, IrfanView is closed and Windows only.

**Comment by Tosh0kan** [comment] 2022-03-03 00:45
It's dead Jim

**Comment by PeterDaveHello** [comment] 2022-03-12 21:10
Maybe this issue is just a duplicate of #612

**Comment by abma** [comment] 2022-03-13 00:12
it doesn't matter if this is a duplicate issue or not: someone needs to fork and maintain it.

**Comment by 57382** [comment] 2022-04-08 03:23
update
https://github.com/nomacs/nomacs/issues/612#issuecomment-1084678367

**Comment by leejuyuu** [comment] 2024-07-06 09:28
Please continue discussion at https://github.com/nomacs/nomacs/issues/987.

**Closed by leejuyuu** 2024-07-06 09:28 UTC
