### ISSUE TITLE
Resize function increase size of image but shouldn’t

### ISSUE THREAD

**Issue by Arcat694** [nomacs/nomacs#687] opened 2021-06-05 18:59 UTC
Type (Severity): S3 Major
Priority: P2 Medium
Assigned to: Author “https://nomacs.org”
Title: Resize function increase size of image but shouldn’t
Version: 3.16 (current)
Environment: PC
Steps:
1.	open the program
2.	open the image
3.	open adjustments
4.	open rotation function
5.	choose resize function
6.	back at rotation function

Actual result: the image will become larger with ratio x1 for resize function
Expected Result: the image will not become larger with ratio x1 for resize function

**Comment by scrubbbbs** [comment] 2024-09-01 15:36
I cannot reproduce this. However, clicking on any adjustment will immediately apply the adjustment. It doesn't matter if the image was modified or not. You can see this happening in the history panel. Closing since this is the design of the adjustment panel.

**Closed by scrubbbbs** 2024-09-01 15:36 UTC
