### ISSUE TITLE
Bad Crop

### ISSUE THREAD

**Issue by hpytree** [nomacs/nomacs#921] opened 2023-02-06 12:19 UTC
![nomacs_bNzQRpPOXz](https://user-images.githubusercontent.com/86867019/216969514-ba1e05ac-5aa0-4a39-89a0-0e6f4dc5e16c.gif)

**Comment by c0xc** [comment] 2023-05-01 21:11
This is a duplicate of: issue #850 

Please try the latest dev version ([download for Windows](https://ci.appveyor.com/api/buildjobs/xgbakr7j49mh4fgx/artifacts/installer%2Fnomacs-portable-win.zip)).

**Comment by leejuyuu** [comment] 2024-01-28 09:20
@hpytree Does the latest dev build works correctly for you?

**Closed** 2024-02-17 19:41 UTC
Labels: duplicate
