### ISSUE TITLE
Exif data remover

### ISSUE THREAD

**Issue by WarcraftSimp** [nomacs/nomacs#1003] opened 2023-11-07 08:32 UTC
Hi im a new user of github, making my account for this request. And Nomacs is amazing but what I am missing is a tool to remove exif data from my pictures so I can safely post my pictures online. If it would have that, then Nomacs would be truly complete in my opinion. 

I actually thought that Nomacs could already do this, but I could not find it so to me it seems like its missing indeed. I am no coder so I do not know how hard it is to implement this, so I hope this is possible. 

Thanks

**Comment by leejuyuu** [comment] 2024-11-02 17:03
Closing as duplicate of https://github.com/nomacs/nomacs/issues/624. Please continue the discussion there.

**Closed by leejuyuu** 2024-11-02 17:03 UTC
Labels: duplicate, enhancement
