### ISSUE TITLE
Scan Folder Recursive no longer works

### ISSUE THREAD

**Issue by drawson1** [nomacs/nomacs#797] opened 2021-08-08 10:28 UTC
I've just updated to version 3.16 as part of an openSUSE upgrade; recursive scanning no longer works.

If I have:

Folder
   | - sub1
   | - sub2

and I select "Folder", only the files in "sub1" are found and displayed; the program never recurses into "sub2"

**Comment by derkork** [comment] 2021-11-01 20:16
Same problem on Windows, version 3.16.

**Comment by anarcat** [comment] 2024-08-18 04:45
> I've just updated to version 3.16 as part of an openSUSE upgrade; recursive scanning no longer works.

could you clarify what version you updated *from*?

**Comment by anarcat** [comment] 2024-08-18 05:12
@novomesk i think this is a dupe of #297.

**Comment by leejuyuu** [comment] 2024-08-18 05:52
Closing as duplicate, please continue the discussion at #297.

**Closed by leejuyuu** 2024-08-18 05:52 UTC
Labels: duplicate
