### ISSUE TITLE
Rotate buttons do not rotate image when selected.

### ISSUE THREAD

**Issue by CaptainMorgan12** [nomacs/nomacs#998] opened 2023-10-04 15:12 UTC
Environment: Ubuntu 23.04, Nomacs 3.17.2204, Wayland.

Steps to repeat:
1. open large .png image ~200MB, but any other .jpeg image will do
2. select rotate in right menue
3. select one of the rotate left or right buttons

Observe no image rotation.

When the user selects the free rotation slider or enters a number 90deg, 180deg the image rotates as expected.

**Comment by leejuyuu** [comment] 2024-11-02 17:35
Confirmed on 3.19.1 (ba263741), Arch Linux, Qt 6.8.0. In my case, it works for clicking twice but stops afterwards.

**Comment by scrubbbbs** [comment] 2024-11-10 13:11
> When the user selects the free rotation slider or enters a number 90deg, 180deg the image rotates as expected.

It sounds like you are describing the rotation *adjustment* panel (from the "Adjustments/Rotate..." menu). The rotation adjustment does not have a rotate left/right button, those are the back/forward on the edit history.

But I can see the confusion as it has the same icon as the rotate left/right action in the toolbar/edit menu. I think a left/right arrow would be better here.

**Comment by leejuyuu** [comment] 2024-11-11 12:55
You're right, I also got caught by undo/redo and rotate icon confusion 😂.

**Comment by leejuyuu** [comment] 2024-11-11 12:57
So this is not necessarily a bug. Also, it's duplicate of #718.

**Comment by leejuyuu** [comment] 2024-11-11 12:58
Closing this one, please continue discussing at #718.

**Closed** 2024-11-11 12:58 UTC
Labels: duplicate
