### ISSUE TITLE
DNG Raw photos are displayed too dark

### ISSUE THREAD

**Issue by Thane5** [nomacs/nomacs#754] opened 2021-07-11 15:31 UTC
**Describe the bug**
HDR photos (in the .dng format) appear too dark when opened in Nomacs

**Expected behavior**
The displayed image should be brighter to better show its content. With the current settings details in dark areas are often barely visible.
Other image viewers like windows photo viewer or XnView show a more useful, brighter version of that image.

**Screenshots**
I took a screenshot of an image in both Nomacs and XnView to compare them:
**[Imgur Link](https://i.imgur.com/YmBtHia.png)**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1 (10.0.19043 Build 19043)

**Comment by C0rn3j** [comment] 2024-02-26 09:15
https://github.com/nomacs/nomacs/issues/285

https://github.com/nomacs/nomacs/issues/459

Probably a dupe of one of these two issues

**Closed** 2024-08-30 20:43 UTC
Labels: duplicate
