### ISSUE TITLE
[Request] Update nomacs against the latest opencv and python-opencv

### ISSUE THREAD

**Issue by rado84-github** [nomacs/nomacs#1112] opened 2024-06-27 15:16 UTC
**Describe the bug**
opencv & python-opencv have new versions, nomacs won't run with their latest version

**To Reproduce**
1. Update opencv & python-opencv to the latest version which is 4.10.0.
2. Open terminal and type $ nomacs.
3. You'll see a message that nomacs is missing a library with version .409.

**Expected behavior**
Nomacs should be updated to work with the latest opencv & python-opencv.

**Screenshots**
Not necessary for this.

**Desktop (please complete the following information):**
OS: Arch
DE: Cinnamon 6.2.0.

**Additional context**
The only way to fix the problem is to downgrade both opencv & python-opencv to versions 4.9.0. Then nomacs works fine.
Personally, I have no problem to use nomacs like this. But opencv is a dependency of a dozen other packages, including gcc-libs and there's no telling what will happen to the system if one of those packages some day update and require opencv 4.10 or 4.11. One thing is certain though - in that case nomacs will stop working. That's why I'm posting this request to update nomacs with the latest opencv and python-opencv.

**Comment by leejuyuu** [comment] 2024-06-27 15:18
Hello, how did you install nomacs on your system? Maybe we can help you recompile the package if you provide more description.

**Comment by leejuyuu** [comment] 2024-06-27 15:22
This is a duplicate of https://github.com/nomacs/nomacs/issues/1105.

**Comment by rado84-github** [comment] 2024-06-28 19:22
I had forgotten I had already reported it.
As for how I installed it - from AUR.

**Comment by leejuyuu** [comment] 2024-06-29 02:11
When the libraries that nomacs depends on get updated, the nomacs AUR package needs to be rebuilt. Increase the pkgrel in the PKGBUILD, and run `makepkg -sic` again.

**Comment by leejuyuu** [comment] 2024-07-06 08:23
I am closing this as this is not fixable on our side.

**Closed by leejuyuu** 2024-07-06 08:23 UTC
Labels: duplicate
