### ISSUE TITLE
Touchpad gesture support

### ISSUE THREAD

**Issue by alexchexes** [nomacs/nomacs#1189] opened 2024-11-13 17:59 UTC
**Is your feature request related to a problem? Please describe.**
Not sure.

**Describe the solution you'd like**
Support for common touchpad gestures, such as pinch-to-zoom, two-finger swipe for next/previous navigation and so on.

**Describe alternatives you've considered**
Using other software?

**Additional context**
I’m not sure if gestures are also missing on macOS, but if they are, that would be surprising. So, I’m asking to add support for them on Windows as well.

**Comment by scrubbbbs** [comment] 2024-11-13 19:37
Duplicate of #365. Thanks for reporting. There is [some gesture code](https://github.com/nomacs/nomacs/blob/864bb5b9cf18cde0d6f87c5eeaeff8ce81505dd2/ImageLounge/src/DkCore/DkBaseViewPort.cpp#L381) but it does not seem to be complete. If I'm reading it correctly, the pinch gesture should work - I'm not sure if this is only for touch-screen devices or trackpads, or if those are the same thing in Qt.

**Closed** 2024-11-13 19:38 UTC
