### ISSUE TITLE
"Confirm on delete" setting in GUI

### ISSUE THREAD

**Issue by eighttails** [nomacs/nomacs#920] opened 2023-01-22 01:41 UTC
nomacs shows confirm dialog when deleting file.
![image](https://user-images.githubusercontent.com/4285709/213896644-c2fc1492-46d3-4538-8af7-053901699b9c.png)
If I check "Remember my choice" this dialog never appears.

But there is no way to revert this config in setting GUI.
I have to edit `~/.config/nomacs/Image Lounge.conf`.

**Comment by scrubbbbs** [comment] 2024-07-18 13:04
Related #761

**Comment by leejuyuu** [comment] 2024-11-02 17:25
Closing as duplicate of https://github.com/nomacs/nomacs/issues/761.

**Closed by leejuyuu** 2024-11-02 17:25 UTC
Labels: duplicate, enhancement
