### ISSUE TITLE
Program crashes when opening any image file

### ISSUE THREAD

**Issue by jestarray** [nomacs/nomacs#540] opened 2020-08-13 06:11 UTC
No idea what's causing it to but any image file that I open crashes...
video:
https://i.imgur.com/ks8sgSY.mp4

CLI dump:
```
[INFO] Hi there
[INFO] plugins dir set to:  "/usr/lib/nomacs-plugins"
[INFO] local client created in:  2 ms
[INFO] theme loaded from "/usr/share/nomacs/Image Lounge/themes/Light-Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
terminate called after throwing an instance of 'QUnhandledException'
  what():  std::exception
fish: “nomacs ashlands_tileset.png” terminated by signal SIGABRT (Abort)
```
Platform: Arch Linux
nomacs version: 3.17

Tell me if there are any more logs I can submit

**Comment by diemmarkus** [comment] 2020-08-13 07:10
that is most likely a duplicate of #537 - I will draft a new beta release today that fixes this issue...

**Comment by jestarray** [comment] 2020-08-13 15:10
Alright thanks, flagged arch linux package out of date so it can upgrade, feel free to close. Turning off anti aliasing fixes it as mentioned

**Closed** 2020-08-13 20:59 UTC
