### ISSUE TITLE
Image doesn't update when moving to next image

### ISSUE THREAD

**Issue by peterfreeth** [nomacs/nomacs#1191] opened 2024-11-16 11:30 UTC
When viewing a number of jpeg files in a folder and using either the keyboard left and right arrow keys to move forwards and backwards through the list of images or the on screen left and right arrows, every so often, the screen image does not update. The display flashes but stays on the previous image. If I click through very slowly it's OK.

The image stays the same as the previously viewed image but the title bar shows the correct new image. I use nomacs to cull photos from events and this problem means that if I then delete an image, I'm deleting the wrong one and this is a major problem. I like to use nomacs because of the way that it can show exif data alongside the image.

3.17.2282 on Ubuntu 24.10 all up to date, but this has always been the problem with nomacs for the last year or two that I have been using it.

Steps to reproduce:

Open a folder with images and open the first one in nomacs
Scroll through the images using either the on screen or keyboard right arrow, click through faster than once per second
Notice that, every few images, the display flashes briefly but the image does not update, although the file name in the title bar has updated

What should happen is that the image displayed should always be the one shown in the title bar.

**Comment by leejuyuu** [comment] 2024-11-16 14:30
Thanks for reporting. I am closing this one because it seems like a duplicate of https://github.com/nomacs/nomacs/issues/1001. Please continue the discussion there.

**Closed** 2024-11-16 17:21 UTC
Labels: duplicate
