### ISSUE TITLE
Bug: File ratings not updated

### ISSUE THREAD

**Issue by nanatsuhachi** [nomacs/nomacs#1018] opened 2024-01-25 06:29 UTC
**Translated at DeepL.

I have updated nomacs to the latest version and the ratings I have made on nomacs are not reflected in the image files and revert back to before the ratings.
The OS is Win11 and the file I am trying to manipulate is a JPEG.

**Comment by leejuyuu** [comment] 2024-02-17 17:36
Thanks for the report! Because this is a duplicate of #909, I will close this issue. Please head to the linked issue for further discussions.

**Closed by leejuyuu** 2024-02-17 17:36 UTC
Labels: duplicate
