### ISSUE TITLE
Option to open in fullscreen mode by default

### ISSUE THREAD

**Issue by BakedCookie** [nomacs/nomacs#1109] opened 2024-06-26 00:35 UTC
**Is your feature request related to a problem? Please describe.**
My preferred way of viewing images is to launch them straight into fullscreen mode. This option exists if launching nomacs from the command line (with the -f flag), but there's no way to set that in the settings so that it could work when double clicking images.

**Describe the solution you'd like**
A "Launch in fullscreen" checkbox in the settings menu.

**Describe alternatives you've considered**
Currently I can achieve the desired effect by modifying the windows registry:
```
navigate to
HKEY_CLASSES_ROOT\nomacs.jpg.3\shell\open\command

modify value data from
"C:\Program Files\nomacs\bin\nomacs.exe" "%1"

to

"C:\Program Files\nomacs\bin\nomacs.exe" "-f" "%1"

repeat for other formats
```

This is obviously far from ideal and it would be nice to have a checkbox in the settings menu. Especially since the functionality is already there.

**Additional context**
N/A

**Comment by leejuyuu** [comment] 2024-06-29 08:38
I am closing this issue because it is a duplicate of https://github.com/nomacs/nomacs/issues/550. Please discuss this there, thanks!

**Closed by leejuyuu** 2024-06-29 08:38 UTC
Labels: duplicate
