### ISSUE TITLE
Inconsistent coordinate reporting within the Nomacs application

### ISSUE THREAD

**Issue by sjoro** [nomacs/nomacs#1138] opened 2024-07-25 09:28 UTC
I'm working with satellite images and I often need to crop many images in one go and batch processing in Nomacs seems like a good way to do it. I'd like to have an easy and consistent way to draw the cropped area, mark down the x, y, width, height and use the values in batch processing. It would be even better if I could somehow copy-paste the crop values from crop toolbar directly to batch processing tool.

The crop toolbar coordinates seem to report the center pixel x, y for the selected crop in an image. These values, when used in batch processing, do not yield the correct crop.

**Describe the bug**
Coordinates reported in crop toolbar  and on the statusbar are different for the drawn cropped area. Values in status bar seem to yield correct crop area in batch processing. The problem with statusbar x, y values is that they disappear when switching to batch processing (user needs to mark them down immediately). The crop toolbar remains visible, but does not yield correct results.

**To Reproduce**
1. Open an image and draw a rectangle to be cropped
2. Mark down the x, y, width, and height shown on the crop toolbar
3. Mark down the x, y on the statusbar (they are different form the toolbar)
4. Use the crop toolbar x, y values in batch processing for the same image
5. Notice that the batch produced image is not the same cropped area as what was drawn in the original image
6. Repeat with the statusbar x, y values and verify that the copped area is as desired

**Expected behavior**
Use the same coordinate reporting everywhere in the software (toolbar, statusbar, batch processing) so that the produced images are always the same. Even better if there would be a way to copy-paste the values directly to batch processing avoiding manual typing errors and avoiding an extra step in the workflow.

**Screenshots**
#### Example GUI screenshot
<img width="1453" alt="Screenshot 2024-07-25 at 10 56 03" src="https://github.com/user-attachments/assets/05efcebf-a97e-4cd8-86f0-f184a704bf1b">

#### Batch processing image produced with toolbar values (x: 10370, y: 3905, width: 1614, height: 775)
![coordinates_crop_tool](https://github.com/user-attachments/assets/38ce14b2-23fb-493f-aeb3-984886cf52a8)

#### Batch processing image produced with statusbar values (x: 9563, y: 3517, width: 1614, height: 775)
![coordinates_status_bar](https://github.com/user-attachments/assets/ab6fe9e1-168f-4370-b853-c5729c9eb63b)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: Sonoma 14.5
 - Nomacs version 3.16.0

**Comment by leejuyuu** [comment] 2024-07-25 09:47
This is a duplicate of #944, which was fixed by #1070. Please try the latest testing version (3.19.0).

**Comment by sjoro** [comment] 2024-07-25 10:53
hi @leejuyuu 
thanks for pointing that out, i quickly browsed the issues, but didn't catch that existing issue.

i just installed 3.19.0, now the batch processing fails
```
processing /Users/xxx/Downloads/FCI_hres_OPE__true_color_flames_20240723T033000.png
[Transform Batch] image 22272 x 22272 cropped to x12971 y3334 w1880 h1136
Original filename added to Exif
Could not save: /Users/xxx/Downloads/cropped/FCI_hres_OPE__true_color_flames_20240723T033000
Ui - a lot of things went wrong. Your original file can be found here: 
Unknown error
I did not delete the original because I detected 2 failure(s).
```

**Comment by leejuyuu** [comment] 2024-07-25 16:49
I opened another issue (#1139) for the batch regression. This one will be closed for now.

**Closed by leejuyuu** 2024-07-25 16:49 UTC
Labels: duplicate
