### ISSUE TITLE
exception c0000005 at 00007ffed1bf3cda

### ISSUE THREAD

**Issue by gerroon** [nomacs/nomacs#444] opened 2020-03-19 00:30 UTC
**Describe the bug**
Nomaccs closes as soon as it opens 

**To Reproduce**
Open an image with double clicking or or open nomacs direclty

**Expected behavior**
It should just open properly

**Screenshots**
I am not fast enough to grab one

**Desktop (please complete the following information):**
Windows 10 x64, Nomacs 3.14.4805

**Additional context**
Since it crashes right away there is no info on why, I tried to use Msys Strace to see where it crashes. See the log please

https://bin.privacytools.io/?55b96426fd011c13#jXB7wJ8MxsjQfGwpzUqGrhm0EdiWSL4YioWGe/vGlck=

**Comment by diemmarkus** [comment] 2020-03-19 07:48
sorry man...
can you send me your settings please?
- open a windows explorer and type %appdata%
- open nomacs/ImageLounge
- there, I would need settings.ini 
*NOTE*: there might be private data like file paths and file names. you can remove these entries before sending...

then you could try to wipe your settings:
- rename settings.ini to settings-old.ini

**Comment by gerroon** [comment] 2020-03-20 01:33
Hi

I am sure it will be fine if I reset this since this already happened to me 3 times. iut would be nice if I do not have to reset my settings, I lost quite  abit of custom settings like many shortcuts before ;( 

https://bin.privacytools.io/?7d0e7f53a007cedc#1OFFncZHq0B9gbnrHj4AjVtjRc8wjyDy0w1PlnReFXc=

**Comment by diemmarkus** [comment] 2020-03-24 12:38
I just checked it - it does not crash on my side with the very same settings. So I guess it's related to the images in the recent files and/or as you say samba (which I use myself without any issues). does this settings file (without file history) crash too?

**Comment by diemmarkus** [comment] 2020-06-26 12:58
I'll close this issue - since it is not reproducible, sorry!

**Closed by diemmarkus** 2020-06-26 12:58 UTC
Labels: bug, feedback
