### ISSUE TITLE
Add support for jxr images

### ISSUE THREAD

**Issue by NCSGeek** [nomacs/nomacs#1162] opened 2024-09-13 21:53 UTC
**Is your feature request related to a problem? Please describe.**
Right now, nomacs fails to load .jxr images I have from nvidia's screenshot feature

**Describe the solution you'd like**
It'd be nice if nomacs could load these.

**Comment by leejuyuu** [comment] 2024-09-14 07:17
I am going to close this as a duplicate of https://github.com/nomacs/nomacs/issues/969. You would need Qt Image Plugin for JPEG XR.

**Closed by leejuyuu** 2024-09-14 07:17 UTC
Labels: duplicate

**Comment by NCSGeek** [comment] 2024-10-05 02:15
Apologies, I missed that old issue.

**Comment by RandomDude4** [comment] 2024-12-12 11:21
These are unrelated issues, JXR is not the same as JXL. Please re-open this issue as I have the same problem.

Screenshots/print-screens on HDR enabled monitors default to JXR in at least Windows 11. This is because normal JPEG or JPEG XL cannot store HDR information (at least that is my understanding)
