### ISSUE TITLE
Image does not load (error message)

### ISSUE THREAD

**Issue by fichtennadel** [nomacs/nomacs#263] opened 2018-10-04 15:10 UTC
A particular image does not load in nomacs 3.10.2.1917 x64 (on Win7 x64)
Error message "Sorry, I could not load: 20180927_182008.jpg"

I've uploaded the image at [removed]

Please let me know, when the upload is not needed anymore, so I can delete it then.

**Comment by diemmarkus** [comment] 2018-10-05 08:52
thanks for reporting - I have downloaded the image...

**Comment by diemmarkus** [comment] 2018-10-05 09:31
this is related to the Samsung panorama software. I will have a look if we can fix this...
the thing is, that Samsung really seems to break the jpg standard here (which is actually a pretty bad thing to do: https://github.com/libjpeg-turbo/libjpeg-turbo/issues/163).

there seems to be a (python) workaround here: https://gist.github.com/bcyrill/e59fda6c7ffe23c7c4b08a990804b269

duplicate of #254 

here is some data for me:
````
[INFO] loading C:/data/img/nomacs-debug/#263/20180927_182008.jpg
Exif------------------------------------------------------------------
"Exif.Image.ImageWidth"  is  "0"
"Exif.Image.ImageLength"  is  "0"
"Exif.Image.Make"  is  "samsung"
"Exif.Image.Model"  is  "SM-G950F"
"Exif.Image.Orientation"  is  "1"
"Exif.Image.XResolution"  is  "72/1"
"Exif.Image.YResolution"  is  "72/1"
"Exif.Image.ResolutionUnit"  is  "2"
"Exif.Image.Software"  is  "G950FXXU3CRGH"
"Exif.Image.DateTime"  is  "2018:09:27 18:20:08"
"Exif.Image.YCbCrPositioning"  is  "1"
"Exif.Image.ExifTag"  is  "238"
"Exif.Photo.FNumber"  is  "17/10"
"Exif.Photo.ExposureProgram"  is  "2"
"Exif.Photo.ExifVersion"  is  "48 50 50 48"
"Exif.Photo.DateTimeOriginal"  is  "2018:09:27 18:20:08"
"Exif.Photo.DateTimeDigitized"  is  "2018:09:27 18:20:08"
"Exif.Photo.MaxApertureValue"  is  "153/100"
"Exif.Photo.MeteringMode"  is  "1"
"Exif.Photo.Flash"  is  "16"
"Exif.Photo.FocalLength"  is  "420/100"
"Exif.Photo.ColorSpace"  is  "1"
"Exif.Photo.PixelXDimension"  is  "0"
"Exif.Photo.PixelYDimension"  is  "0"
"Exif.Photo.ExposureMode"  is  "0"
"Exif.Photo.WhiteBalance"  is  "0"
"Exif.Photo.FocalLengthIn35mmFilm"  is  "26"
"Exif.Photo.SceneCaptureType"  is  "1"
"Exif.Photo.ImageUniqueID"  is  "F"
"Exif.Image.GPSTag"  is  "512"
"Exif.GPSInfo.GPSLatitudeRef"  is  "N"
"Exif.GPSInfo.GPSLatitude"  is  "53/1 25/1 42/1"
"Exif.GPSInfo.GPSLongitudeRef"  is  "E"
"Exif.GPSInfo.GPSLongitude"  is  "14/1 33/1 51/1"
"Exif.Thumbnail.ImageWidth"  is  "496"
"Exif.Thumbnail.ImageLength"  is  "280"
"Exif.Thumbnail.Orientation"  is  "1"
IPTC------------------------------------------------------------------
XMP------------------------------------------------------------------

[WARNING] Invalid SOS parameters for sequential JPEG
[WARNING] Unsupported marker type 0x6f
[WARNING] Invalid SOS parameters for sequential JPEG
[WARNING] Unsupported marker type 0x6f
[WARNING] could not load "C:/data/img/nomacs-debug/#263/20180927_182008.jpg"
````

**Comment by fichtennadel** [comment] 2018-10-05 09:50
Would be great if nomacs could be made more tolerant, Windows Photo Viewer and IrfanView load the image without any hassle.

**Comment by diemmarkus** [comment] 2018-10-05 14:11
It seems that I could fix this issue. It would be cool if you could test the new [beta](http://download.nomacs.org/nomacs-setup-x64-beta.msi) with your images

**Closed** 2018-10-05 14:11 UTC

**Comment by fichtennadel** [comment] 2018-10-08 09:59
fix in beta confirmed, thanks!
