### ISSUE TITLE
Feature request - word wrap long metadata strings

### ISSUE THREAD

**Issue by juren53** [nomacs/nomacs#979] opened 2023-08-17 00:20 UTC
Long metadata strings e.g. titles, descriptions, etc. currently run off screen.  Users can scroll right and left but when reviewing hundreds to thousands of images in a post-processing inspection, word wrapping these fields would be extremely helpful and time saving.

**Comment by leejuyuu** [comment] 2024-01-28 09:07
Closing this as duplicate of #959.

**Closed** 2024-01-28 09:07 UTC
Labels: duplicate, enhancement
