### ISSUE TITLE
Nomacs crashes when opening normal JPEG-image

### ISSUE THREAD

**Issue by jhappone** [nomacs/nomacs#160] opened 2017-10-04 20:48 UTC
Hi!

Nomacs crashes when opening a certain JPG-image (example in attachment). Windows photo viewer opens image with no problems. Picture is taken with Sony Xperia Z5 compact. I have no clue what could cause this.

![dsc_1630](https://user-images.githubusercontent.com/7497296/31198759-0cd681be-a95e-11e7-88ae-91c17a677325.JPG)

Br,
Jukka

**Comment by diemmarkus** [comment] 2017-11-02 09:34
if you close all metadata panels - nomacs won't crash for now (the issue is fixed in the upcoming release)
thanks!

**Closed by diemmarkus** 2017-11-02 09:34 UTC
