### ISSUE TITLE
Status bar is not shown on start

### ISSUE THREAD

**Issue by tkzv** [nomacs/nomacs#1012] opened 2024-01-11 20:22 UTC
**Describe the bug**
When I start Nomacs, statusbar is absent, even though it is marked as enabled in the menu. If I disable and re-enable it, it works correctly. After I close Nomacs and start it again, there is no status bar again.

**To Reproduce**
1. Close all Nomacs windows.
2. Start Nomacs, enable "Panels → Toolbars → Statusbar", close Nomacs.
3. Either start Nomacs, then open an image file; or start Nomacs with an image file in the command line — the statusbar is absent (incorrect).
4. Check the state of "Panels → Toolbars → Statusbar" —  there is a checkmark next to "Statusbar" (correct).
5. Disable, then enable the statusbar, either through the menu or with Ctrl-I — the status bar appears (correct).

**Expected behavior**
If the statusbar is enabled in the settings, it should appear under the image right from the start.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux AMD64 
 - Versions: kernel 5.15.32-gentoo-r1, sys-libs/glibc-2.38-r9, dev-qt/qtsvg-5.15.11, dev-qt/qtcore-5.15.11-r1, dev-qt/qtwidgets-5.15.11-r1, media-gfx/nomacs-3.16.224-r6

**Additional context**
Console output for steps 3-5:
```
$ nomacs cat3weyes.png 
[INFO] Hi there
[INFO] plugins dir set to:  "/usr/lib64/nomacs-plugins"
[INFO] local client created in:  4 ms
[INFO] theme loaded from "/usr/share/nomacs/Image Lounge/themes/Light-Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[INFO] Initialization takes:  136 ms
[INFO] [DkImageLoader] 68 containers created in 2 ms
[INFO] [DkImageLoader] after sorting:  3 ms
[INFO] [Basic Loader] "/home/oleg/drop/images1/cat3weyes.png" loaded in 5 ms
[INFO] [Basic Loader] "/home/oleg/drop/images1/ccc9e6d88dd0001359300c162a8e89e3.gif" loaded in 9 ms
```

**Comment by leejuyuu** [comment] 2024-02-17 17:44
Thanks for reporting! I reproduced this with 3.17.2287 on Arch Linux. I also edited the title to add more details.

**Comment by scrubbbbs** [comment] 2024-07-20 13:55
I cannot reproduce on 3.19 /  485f97988 / Ubuntu 24.04

99e7a5878 was the last version that seemed to touch statusbar visibility which was before 3.14, so this may not be fixed. There seem to be quite a few bugs with settings, maybe it is related to some systemic issue there.

**Comment by tkzv** [comment] 2024-08-24 05:38
> I cannot reproduce on 3.19 / [485f979](https://github.com/nomacs/nomacs/commit/485f97988417101e1f8ea892f9572be12f39d89d) / Ubuntu 24.04

Works for me with Qt 5.15.14. Could it have been a Qt bug?

**Comment by scrubbbbs** [comment] 2024-08-24 12:25
@tkzv I don't think it is/was a Qt bug. There are many bug opportunities with mode switching, settings, and  panel/toolbar hiding iterations.

3c8a850 (after version you tested) had some additional fixes for status bar visibility when switching modes. My feeling is the bug could be resolved but not necessarily.

**Comment by tkzv** [comment] 2024-09-01 08:38
@scrubbbbs , I mean it stopped manifesting, even though I'm still using the same version of Nomacs 3.16.224 (recompiled when I updated the system, though). Beyond that, I don't know.

**Comment by scrubbbbs** [comment] 2024-09-01 11:52
@tkzv thanks for clarifying. I think we might have a bug when saving or loading settings that can manifest in different ways. I've linked this issue there. Related #912

**Comment by leejuyuu** [comment] 2024-11-02 17:49
I can no longer reproduce the issue on 3.17.2287, Arch Linux, Qt 5.15.15.  It might be a bug in the dependencies. Let's close this for now. Feel free to reopen if it appears again.

**Closed by leejuyuu** 2024-11-02 17:49 UTC
Labels: bug
