### ISSUE TITLE
nomacs  crashes every time opening a specific image

### ISSUE THREAD

**Issue by bebinalpha** [nomacs/nomacs#150] opened 2017-08-29 12:28 UTC
nomacs  crashes every time opening a specific image. This happens to only specific images. nomacs throws a error i have attached the screenshot of the error .  

Window 10 64 bit operation system
Intel i7
32 gb ram

![bug_crash](https://user-images.githubusercontent.com/12027043/29820406-fdee3806-8ce1-11e7-9303-13487352a052.PNG)

**Comment by diemmarkus** [comment] 2017-08-29 15:07
thanks for reporting - could you provide such an image? (if the content is not private, you can upload it here or send us an e-mail)

**Comment by bebinalpha** [comment] 2017-08-29 18:23
Here are the two image files which cause crashing
[bug.zip](https://github.com/nomacs/nomacs/files/1261269/bug.zip)

**Comment by diemmarkus** [comment] 2017-09-15 19:23
confirmed, thanks! The issue seems to be fixed in the current beta: http://download.nomacs.org/msi-setup/nomacs-setup.msi

**Closed** 2017-09-15 19:23 UTC
