### ISSUE TITLE
3.16.* - unclear version

### ISSUE THREAD

**Issue by tieugene** [nomacs/nomacs#530] opened 2020-07-20 11:09 UTC
1. '[News](https://nomacs.org/category/releases/)' says: "Last release is 3.16"
2. '[Release](https://github.com/nomacs/nomacs/releases)' page says: '3.16'
2. Help - About says: "3.16.0"
3. Sources are 'nomacs-3.16.224.*'
The question is: what is current nomacs version?

**Comment by dvzrv** [comment] 2020-07-20 11:43
I have to second this. I have updated the nomacs package on Arch Linux to a version `3.16.1705` for which now no tag exists anymore. Please never delete tags! This breaks reproducibility downstream.
Following with a `3.16.224` which orders *lower* than `3.16.1705` according to [semver](https://semver.org) means also that I will have to downgrade the version by introducing [an epoch](https://wiki.archlinux.org/index.php/PKGBUILD#epoch).

Please follow an incremental versioning scheme and use alpha, beta or rc releases where appropriate instead of introducing a DIY versioning scheme for a short amount of time and then delete a tag.

**Comment by diemmarkus** [comment] 2020-07-20 11:56
I have changed versioning in this release from MAJOR.MINOR.PATCH.BUILD to MAJOR.MINOR.BUILD. the advantage is that installers now have the same version as nomacs. But the new release workflow has introduced some noise - including deletion of pre-release tags (my fault - sorry for that). @tieugene where can I find 3.16.0? - I think that should not be the case.

**Comment by tieugene** [comment] 2020-07-20 12:11
> @tieugene where can I find 3.16.0? - I think that should not be the case.

"Help - About" menu (? => About Nomacs).

**Comment by tieugene** [comment] 2020-07-20 13:59
> I have changed versioning in this release from MAJOR.MINOR.PATCH.BUILD to MAJOR.MINOR.BUILD.

1. The word 'build' has no sense in the context of sources. They are sources, they are not built.
2. If 'built' == 'snapshot', the they must be numbered _inside_ version. So there must be possible 3.16.224, 3.17.123 etc.
3. but if 'build' == 'snapshot' has increment numeration, then source version has no sense.
4. In addition '-<number>' is used for distribution specific build systems (e.g. current build in Fedora is nomacs-3.14.2-3.<arch>.rpm - 3rd package rebuild of 3.14.2 source).

**Comment by diemmarkus** [comment] 2020-07-27 11:00
>  there is nothing saving this project from adding a tag that orders lower than the one before again

currently the workflow is like this: 
- every time the project is built, the "build" number in ``version.cache`` is incremented. 
- this file is committed together with the changes - so it should be the same everywhere (you can also refer to it as snapshot). 
- this number is monotonically increasing (as said, the 224 tag was my mistake -> this was the first release that was generated using appveyor).

>     2\. So there must be possible 3.16.224, 3.17.123 etc.

I don't understand all points... but this example is true (and was) for nomacs versioning: so the last number is only guaranteed to be monotonically increasing within its minor version.

@tieugene as said: 3.16.0 seems to be a cmake issue -> I'll investigate that (did you build it yourself?).

**Closed** 2020-08-04 06:55 UTC
