### ISSUE TITLE
Deleting an image causes browsing to stop

### ISSUE THREAD

**Issue by Welding-Torch** [nomacs/nomacs#805] opened 2021-09-03 17:31 UTC
**Describe the bug**
After I delete an image using nomacs, when I try to browse to the next image in the folder it tells me that this is the only image in the folder

**To Reproduce**
1. Open any image in Nomacs on Windows 10 in a folder with multiple images.
2. Press the 'Delete' key on your keyboard.
3. Confirm deletion of the image. Then try to press the right arrow key, and instead of seeing the next image you will be told that you have reached the end of the folder.

**Expected behavior**
I want to be able to delete an image and continue browsing.

**Desktop (please complete the following information):**
Windows 10 20H2

**Additional context**
This bug cripples me when I want to go through a folder with a lot of images and delete some of them.

**Comment by R8s6** [comment] 2023-05-17 18:57
I confirm this error still exists in 3.17.0

**Comment by scrubbbbs** [comment] 2024-07-17 13:29
Duplicate #600

**Comment by scrubbbbs** [comment] 2024-07-17 17:00
@leejuyuu  Given that I could not reproduce the other cases, (delete from front or middle) either they've been fixed or this is the same bug. I should have mentioned this due to the ambiguity.

**Comment by leejuyuu** [comment] 2024-07-17 17:02
Got it. Let's close this then.

**Closed by leejuyuu** 2024-07-17 17:02 UTC
Labels: duplicate

**Comment by Welding-Torch** [comment] 2024-07-18 02:21
I thought devs would never see this issue since I made it all the way back in 2021 lol. Thanks for not forgetting about it and taking the time to fix it.
