### ISSUE TITLE
Star Rating not saved

### ISSUE THREAD

**Issue by waynewang1286** [nomacs/nomacs#1026] opened 2024-02-07 18:15 UTC
I can use star rating on any photo, but the rating is lost after you move to next two photos.
It is also NOT saved with the photo file, as I don't see the rating in Windows.

**Comment by leejuyuu** [comment] 2024-02-17 17:36
Thanks for the report! Because this is a duplicate of https://github.com/nomacs/nomacs/issues/909, I will close this issue. Please head to the linked issue for further discussions.

**Closed by leejuyuu** 2024-02-17 17:36 UTC
Labels: duplicate
