### ISSUE TITLE
Part of images is not displayed in ‘Thumbnails’

### ISSUE THREAD

**Issue by annfisher** [nomacs/nomacs#784] opened 2021-07-22 09:40 UTC
**Steps To Reproduce**  
1.	Open nomacs app;
2.	Open image (availability subfolder with image(-s) is required);
3.	Go to File -> Activate Scan Folder Recursive;
4.	Go to Panels -> Activate Thumbnails. 

**Expected behavior**  
Thumbnails shows images from all folders (including subfolders).  
  
**Actual behavior**  
Thumbnails shows images from current folder (not including subfolders).  
  
**Environment**  
 - Windows 10 Home [x64] ver 21H1;  
 - nomacs ver 3.16.1709 [x64].

**Comment by scrubbbbs** [comment] 2024-06-10 20:42
Duplicate of  #297

**Comment by anarcat** [comment] 2024-08-18 05:12
@novomesk dupe of #297.

**Comment by leejuyuu** [comment] 2024-08-18 05:53
Closing as duplicate, please continue the discussion at https://github.com/nomacs/nomacs/issues/297.

**Closed by leejuyuu** 2024-08-18 05:53 UTC
Labels: duplicate
