### ISSUE TITLE
[Regression] Nomacs no longer respects KDE/Qt font DPI

### ISSUE THREAD

**Issue by geckolinux** [nomacs/nomacs#464] opened 2020-04-10 14:21 UTC
Hi there, I'm using Nomacs 3.14 on openSUSE Tumbleweed (rolling) with Qt 5.14.1.

I've used it for years, but for some reason it has recently stopped respecting my KDE font DPI setting of 108. Sorry that I didn't really notice when this happened, but I know that it used to work, probably within the past month or two something has changed. Here's a comparison of its UI with Kate, which behaves normally:

![Screenshot_20200410_091947](https://user-images.githubusercontent.com/2692138/78997615-876b4680-7b0c-11ea-8874-d14fbef0f2e0.png)

I can work around this with `QT_SCALE_FACTOR=1.2 nomacs`, but this never used to be necessary.

Thanks a lot!

**Comment by diemmarkus** [comment] 2020-04-10 15:00
thanks for reporting. this could be related to #450 (though I don't know what causes these issues)

**Comment by geckolinux** [comment] 2020-04-10 15:17
@diemmarkus Thanks for the reply. Also possibly related to #385 ?

**Comment by mesaprotector** [comment] 2024-06-16 19:24
Hope it's not a breach of etiquette to mention a four year old issue, but I just ran across this today. While I can run nomacs with the relevant environment variable to get the fonts to look correct, this causes zoom percentages to be wrong (ex. a full-screen screenshot will only actually fill the screen at 107%). 

Not sure what causes this either, but I can try different settings if anyone would like. I'm not much of a programmer.

**Comment by leejuyuu** [comment] 2024-06-30 12:23
Could not reproduce the font DPI with Kubuntu 22.04, so I cannot verify what #1102 is fixing. Forced font DPI to 144, the display scaling is 100%.

Top-left: 3.17.2297 (06671c64)
Top-right: 3.19.0 (d768ccda)
Bottom: 3.12 (from ubuntu repo)

![image](https://github.com/nomacs/nomacs/assets/46868116/edec94ff-2827-4411-b3dd-82007526c263)

**Comment by leejuyuu** [comment] 2024-06-30 12:35
About the image scaling, is it correct that image at 100% in nomacs on system display scaled to 150% should look the same when 150% in nomacs on system that displays 100%?

**Comment by scrubbbbs** [comment] 2024-07-06 20:22
The correct way to rescale nomacs UI is to use QT_FONT_DPI=96*scale_factor.

QT_SCALE_FACTOR will have issues as it (by-design) multiplies any system scale factor and nomacs' internal scale factor based on DPI.

**Comment by scrubbbbs** [comment] 2024-07-07 12:35
Scaling working correctly on Kubuntu 24.04 Qt 5.15.13,  3.17.2282 and  3.19  f5a9c5, let's close this.

<img width="575" alt="kubuntu-24 04-kde-scaling" src="https://github.com/nomacs/nomacs/assets/89664476/75e0ed9d-8826-4afc-96ea-3f7685edc981">

3.17 100%
![kubuntu-24 04-3 17 2282-100percent](https://github.com/nomacs/nomacs/assets/89664476/257958b2-c490-47e6-9938-55c66a82ad69)

3.17 150%
<img width="960" alt="kubuntu-24 04-3 17 2282-150percent" src="https://github.com/nomacs/nomacs/assets/89664476/8cc05408-0057-4bac-a587-5738f2383561">

3.19 100%
![kubuntu-24 04-3 19 f5a9c5-100percent](https://github.com/nomacs/nomacs/assets/89664476/a46086f0-4a4d-4199-a30a-68f42b7d6c4f)

3.19 150%
<img width="960" alt="kubuntu-24 04-3 19 f5a9c5-150percent" src="https://github.com/nomacs/nomacs/assets/89664476/8ae58f74-6658-46f9-b3e6-d7ffcba1af34">

**Comment by leejuyuu** [comment] 2024-07-13 07:41
Thanks for testing! I'm closing this for now. Feel free to reopen if there's more to discuss.

**Closed by leejuyuu** 2024-07-13 07:41 UTC
Labels: code rot
