### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [nomacs/nomacs#401] opened 2019-12-03 19:04 UTC
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing nomacs on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by diemmarkus** [comment] 2020-01-08 08:35
I really like the idea of releasing nomacs on flathub. (you might have noticed that we were playing with snaps already). the problem is, that our time for the project is currently very restricted. so I would be very happy if anyone could support us here : )

**Comment by tiazahmd** [comment] 2020-02-21 19:45
> I really like the idea of releasing nomacs on flathub. (you might have noticed that we were playing with snaps already). the problem is, that our time for the project is currently very restricted. so I would be very happy if anyone could support us here : )

What kind of support are you looking for?

**Comment by diemmarkus** [comment] 2020-03-12 15:22
sorry for the late reply...
to speed things up here, we would need a manifest that builds nomacs.

**Comment by diemmarkus** [comment] 2020-03-13 14:32
update: it appears that @egrath already did the [work](https://github.com/egrath/nomacs-flatpak)

**Comment by tiazahmd** [comment] 2020-03-13 15:22
Oh well. Thanks for letting me know.

**Comment by diemmarkus** [comment] 2020-03-17 19:59
I am having a hard time passing the tests for flathub (see [1409](https://github.com/flathub/flathub/pull/1409). Since anyone here knows more about linux and probably flatpak than I do, I figured that maybe you could help me.

as far as I understand the [build error](https://flathub.org/builds/#/builders/57/builds/1242), nomacs does not properly install the app.metadata. I see two options here:
1. change the nomacs.appdata.xml to conform with flathub (does this cause general packaging issues? @agaida)
2. provide an extra xml for flathub. but where do I need to [install this](https://github.com/flathub/flathub/pull/1409/commits/bd71e1c1eb972df951d6d9677f3e0e1012ad4bfa#diff-e871b66cc26369609b580e85aa72e72bR128)?

maybe @egrath could help too?!
thanks!

**Comment by tiazahmd** [comment] 2020-03-19 14:51
I had an in depth look at the code. Some of these issues are quite above my expertise. I don't think I'll be able to dedicate enough time for this at the moment. Don't want to keep anyone hanging - so I'll withdraw myself from the issue.

**Comment by diemmarkus** [comment] 2020-03-19 16:29
thanks. I think we pretty much solved it (with the help of the flathub team : ). So I am waiting for news over there before I finally close this issue...

**Comment by diemmarkus** [comment] 2020-03-20 08:50
https://github.com/flathub/org.nomacs.ImageLounge

**Closed by diemmarkus** 2020-03-20 08:50 UTC
Labels: help-wanted
