### ISSUE TITLE
GIF - show previous frame is very slow

### ISSUE THREAD

**Issue by bugsman** [nomacs/nomacs#363] opened 2019-08-13 08:25 UTC
Show previous frame in animated GIF is VERY slow.
nomacs 3.12, Win7x64

**Comment by xbrakl** [comment] 2019-08-25 10:25
Please provide us the problematic GIF and some more describtion of your problem, so authors can reproduce the bug and find solution.

Make printscreen of that option: "show previous frame" as well. Thanks.

**Comment by bugsman** [comment] 2019-08-25 13:41
![11017982955_7d9946101b_o](https://user-images.githubusercontent.com/54036859/63650731-69142e80-c767-11e9-978d-e940342b4c9c.gif)

![nomacs_21bVjsRt3k](https://user-images.githubusercontent.com/54036859/63650790-ff485480-c767-11e9-8955-d1a8d24edf4c.png)

**Comment by diemmarkus** [comment] 2019-08-26 07:27
thanks for pointing this out. you are right, loading the previous frame is much slower than loading the next frame:
````bash
loading previous frame takes: 413 ms
loading next frame takes: 2 ms
````
the problem here is that [QMovie](https://doc.qt.io/qt-5/qmovie.html#cacheMode-prop) does not provide an interface for loading previous frames - so we have to iterate through all frames of a gif to render the previous frame.

I will close this issue, since there does not seem to be a better way to do so (see [stackoverflow](https://stackoverflow.com/questions/34703114/qt-jumptoframe-is-not-working))

- nice sample btw : )

**Closed by diemmarkus** 2019-08-26 07:27 UTC
